githubRepoOwner: MichaelSims
githubRepoName: git-spr-demo
githubHost: github.com
requireChecks: true
requireApproval: false
githubRemote: origin
githubBranch: main
remoteBranches: []
mergeMethod: rebase
